# This workflow will do a clean install of node dependencies, build the source code and deploy to github pages

name: Node.js CI (Deployment)

on:
  push:
    branches: [ deploy ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run deploy
